---
all:
  children:
    homelab:
      vars:
        user: fouchger
        ansible_user: fouchger
      children:
        local:
          hosts:
            localhost:
              ansible_connection: local
          vars:
            user: root
            ansible_user: root

        proxmox:
          hosts:
            pve01:
              ansible_host: 192.168.88.250

        nas:
          hosts:
            omv01:
              ansible_host: 192.168.88.251

        router:
          hosts:
            mtik01:
              ansible_host: 192.168.88.1

        test:
          hosts:
            admin02:
              ansible_host: 192.168.88.108